from __future__ import annotations

from .models import Canvas, CostTrace, Edge, Node, Source


def _source(title: str, url: str, snippet: str) -> Source:
    return Source(title=title, url=url, snippet=snippet, source="seed")


def datacenter_demo() -> Canvas:
    objective = (
        "Choose the strongest 2027 North American AI inference data-center region while balancing "
        "grid capacity, water stress, clean power, incentives, latency, permitting, community risk, and climate exposure."
    )
    canvas = Canvas(
        id="demo-ai-inference-siting-2027",
        title="ForkLens Demo: AI Inference Data-Center Siting",
        objective=objective,
        lanes=[
            "Objective",
            "Discovery",
            "Northern Virginia",
            "Columbus",
            "Phoenix",
            "Québec / Ontario",
            "Atlanta",
            "Dissent Lane",
            "Human Forks",
            "Recommendation",
        ],
        readme="This seed graph is intentionally marked as a replayable demo. Run ForkLens with a Perplexity API key to refresh every source and claim before sharing publicly.",
    )

    nodes = [
        Node(
            id="objective",
            type="objective",
            title="Decision objective",
            lane="Objective",
            x=80,
            y=90,
            summary=objective,
            confidence=0.92,
            tags=["objective", "high-stakes", "infrastructure"],
            cost=CostTrace(route="human_seed", total_cost_usd=0),
        ),
        Node(
            id="breadth-search",
            type="search_batch",
            title="Cheap breadth pass",
            lane="Discovery",
            x=360,
            y=90,
            summary="Fan out public-data searches for utilities, interconnect queues, power prices, water risk, incentives, permitting, local news, and latency constraints.",
            confidence=0.86,
            tags=["search-api", "breadth", "low-cost"],
            cost=CostTrace(route="search_api", model="search", tool_calls=42, total_cost_usd=0.21, latency_ms=11500),
            details={"why_this_route": "Search API is cheaper than sending every source to a frontier model."},
        ),
        Node(
            id="embed-filings",
            type="source_cluster",
            title="Document ingestion lane",
            lane="Discovery",
            x=360,
            y=250,
            summary="Chunk utility filings, incentive PDFs, council packets, sustainability reports, and public planning documents into reusable source clusters.",
            confidence=0.8,
            tags=["embeddings", "source-cache"],
            sources=[
                _source("EIA electricity data", "https://www.eia.gov/electricity/", "Power-market data source to refresh in live runs."),
                _source("EPA EJScreen", "https://www.epa.gov/ejscreen", "Environmental justice and local exposure source to refresh in live runs."),
                _source("NREL data and tools", "https://www.nrel.gov/research/data-tools.html", "Clean energy and grid-analysis source to refresh in live runs."),
            ],
            cost=CostTrace(route="contextual_embeddings", model="pplx-embed-context-v1-0.6b", input_tokens=118000, total_cost_usd=0.06, latency_ms=9800),
        ),
        Node(
            id="nova-claim",
            type="claim",
            title="Northern Virginia: deployment gravity",
            lane="Northern Virginia",
            x=690,
            y=60,
            summary="Strongest near-term execution path because the ecosystem, fiber, vendors, and data-center labor market are already dense. The risk is that grid and permitting friction may cap marginal expansion.",
            confidence=0.66,
            tags=["speed", "ecosystem", "grid-risk"],
            cost=CostTrace(route="sonar", model="sonar-pro", input_tokens=4200, output_tokens=870, total_cost_usd=0.018, latency_ms=7600),
        ),
        Node(
            id="nova-counter",
            type="counterclaim",
            title="Northern Virginia dissent: saturation risk",
            lane="Northern Virginia",
            x=960,
            y=60,
            summary="The same ecosystem strength creates community, land, grid-upgrade, and political exposure. ForkLens should require evidence that the next 500MW can be permitted, powered, and defended publicly.",
            confidence=0.58,
            tags=["dissent", "permitting", "community-risk"],
            cost=CostTrace(route="deep_research_escalation", model="sonar-deep-research", input_tokens=7800, output_tokens=1900, total_cost_usd=0.11, latency_ms=46000),
        ),
        Node(
            id="columbus-claim",
            type="claim",
            title="Columbus: balanced domestic option",
            lane="Columbus",
            x=690,
            y=190,
            summary="Looks like a credible compromise region: central latency, expandable industrial land, and growing tech manufacturing gravity. Needs utility-specific evidence on interconnection timing and power cost trajectory.",
            confidence=0.62,
            tags=["balanced", "latency", "industrial-land"],
            cost=CostTrace(route="sonar", model="sonar-pro", input_tokens=3900, output_tokens=760, total_cost_usd=0.016, latency_ms=7100),
        ),
        Node(
            id="phoenix-claim",
            type="claim",
            title="Phoenix: solar and speed, water tradeoff",
            lane="Phoenix",
            x=690,
            y=320,
            summary="Attractive if the decision optimizes near-term build speed, solar procurement, and Southwest latency. The water and heat-resilience tradeoff is too load-bearing to hide in a paragraph.",
            confidence=0.6,
            tags=["solar", "water-stress", "heat"],
            cost=CostTrace(route="sonar", model="sonar-pro", input_tokens=4100, output_tokens=810, total_cost_usd=0.017, latency_ms=7400),
        ),
        Node(
            id="canada-claim",
            type="claim",
            title="Québec / Ontario: clean-power upside",
            lane="Québec / Ontario",
            x=690,
            y=450,
            summary="Potentially best for clean-power narrative and long-horizon energy cost, but cross-border latency, customer geography, sovereignty, and procurement friction require explicit scoring.",
            confidence=0.57,
            tags=["clean-power", "cross-border", "latency"],
            cost=CostTrace(route="sonar", model="sonar-pro", input_tokens=4000, output_tokens=790, total_cost_usd=0.016, latency_ms=7300),
        ),
        Node(
            id="atlanta-claim",
            type="claim",
            title="Atlanta: Southeast latency and growth",
            lane="Atlanta",
            x=690,
            y=580,
            summary="A pragmatic Southeast option with strong network reach and business climate. Needs deeper work on utility readiness, climate exposure, and competition for large-load capacity.",
            confidence=0.55,
            tags=["southeast", "network", "utility-readiness"],
            cost=CostTrace(route="sonar", model="sonar-pro", input_tokens=3700, output_tokens=740, total_cost_usd=0.015, latency_ms=6900),
        ),
        Node(
            id="dissent-grid",
            type="counterclaim",
            title="Blind spot: grid queue optimism",
            lane="Dissent Lane",
            x=1030,
            y=220,
            summary="Most glossy siting analyses underweight interconnection delays. The canvas should force a branch where each region shows named utility upgrades, queue exposure, and credible energization dates.",
            confidence=0.74,
            tags=["blind-spot", "grid", "timeline-risk"],
            cost=CostTrace(route="adversarial_search", model="search+sonar", tool_calls=8, input_tokens=2600, output_tokens=620, total_cost_usd=0.051, latency_ms=15600),
        ),
        Node(
            id="dissent-community",
            type="counterclaim",
            title="Blind spot: local legitimacy",
            lane="Dissent Lane",
            x=1030,
            y=360,
            summary="The decision will fail if it treats community opposition as PR cleanup. Local water, noise, transmission, and tax-abatement narratives need to be first-class evidence nodes.",
            confidence=0.7,
            tags=["blind-spot", "community", "trust"],
            cost=CostTrace(route="adversarial_search", model="search+sonar", tool_calls=6, input_tokens=2400, output_tokens=580, total_cost_usd=0.044, latency_ms=14200),
        ),
        Node(
            id="calc-score",
            type="computation",
            title="Weighted decision score",
            lane="Human Forks",
            x=1300,
            y=180,
            summary="Compute three rankings: deployment speed, trust/sustainability, and five-year scalability. Do not collapse them until the human chooses the decision philosophy.",
            confidence=0.79,
            tags=["sandbox", "scoring", "human-in-loop"],
            cost=CostTrace(route="local_sandbox_adapter", model="python", total_cost_usd=0.0, latency_ms=95),
            details={
                "speed_weights": {"grid": 0.35, "permitting": 0.25, "latency": 0.2, "ecosystem": 0.2},
                "trust_weights": {"water": 0.3, "clean_power": 0.3, "community": 0.25, "climate": 0.15},
                "scale_weights": {"grid": 0.3, "land": 0.2, "power_cost": 0.2, "regulatory": 0.15, "latency": 0.15},
            },
        ),
        Node(
            id="fork-philosophy",
            type="fork",
            title="Human fork: what are we optimizing?",
            lane="Human Forks",
            x=1300,
            y=390,
            summary="Pause execution until the user chooses the decision philosophy: fastest credible deployment, lowest trust risk, or best five-year scalability. Each branch produces a different winner.",
            status="needs_human",
            confidence=0.9,
            tags=["fork", "human-decision", "strategy"],
            details={
                "options": [
                    "Fastest credible deployment",
                    "Lowest trust and sustainability risk",
                    "Best five-year scalability",
                ]
            },
        ),
        Node(
            id="recommendation",
            type="decision",
            title="Recommendation: do not pick a winner yet",
            lane="Recommendation",
            x=1630,
            y=260,
            summary="The correct PM artifact is not a single answer. It is a decision surface that shows why Northern Virginia wins speed, Canada may win clean-power trust, and Columbus/Atlanta may deserve the next evidence pass.",
            confidence=0.81,
            tags=["final", "decision-surface", "perplexity-fit"],
            cost=CostTrace(route="agent_synthesis", model="fast-search+sonar-pro", input_tokens=6400, output_tokens=1350, total_cost_usd=0.039, latency_ms=9400),
        ),
        Node(
            id="metrics",
            type="metric",
            title="Token economics ledger",
            lane="Recommendation",
            x=1630,
            y=470,
            summary="Seed run target: under $0.75, first node under 15s, first conflict under 90s, under 15% deep-research escalation, and every final claim tied to source nodes.",
            confidence=0.88,
            tags=["metrics", "token-value-per-watt"],
            details={
                "target_cost_per_objective_usd": 0.75,
                "target_time_to_first_canvas_node_ms": 15000,
                "target_deep_research_escalation_rate": 0.15,
                "target_context_compression_ratio": "5x-10x",
                "target_broken_citation_rate": 0,
            },
        ),
    ]

    edges = [
        Edge("objective", "breadth-search", "decompose", "routes"),
        Edge("objective", "embed-filings", "ingest docs", "routes"),
        Edge("breadth-search", "nova-claim", "region lane", "supports"),
        Edge("breadth-search", "columbus-claim", "region lane", "supports"),
        Edge("breadth-search", "phoenix-claim", "region lane", "supports"),
        Edge("breadth-search", "canada-claim", "region lane", "supports"),
        Edge("breadth-search", "atlanta-claim", "region lane", "supports"),
        Edge("nova-claim", "nova-counter", "stress test", "contradicts"),
        Edge("nova-claim", "dissent-grid", "grid risk", "contradicts"),
        Edge("phoenix-claim", "dissent-community", "water legitimacy", "contradicts"),
        Edge("columbus-claim", "calc-score", "score", "routes"),
        Edge("nova-counter", "calc-score", "risk-adjust", "routes"),
        Edge("dissent-grid", "fork-philosophy", "requires choice", "forks"),
        Edge("dissent-community", "fork-philosophy", "requires choice", "forks"),
        Edge("calc-score", "fork-philosophy", "ranking depends on weights", "forks"),
        Edge("fork-philosophy", "recommendation", "selected strategy", "resolves"),
        Edge("recommendation", "metrics", "prove efficiency", "supports"),
    ]

    canvas.nodes = nodes
    canvas.edges = edges
    canvas.metrics = {
        "estimated_total_cost_usd": round(sum((node.cost.total_cost_usd if node.cost else 0) for node in nodes), 3),
        "estimated_latency_ms_sum": sum((node.cost.latency_ms or 0) for node in nodes if node.cost),
        "deep_research_escalation_rate": 1 / 11,
        "frontier_token_displacement": "Search and embeddings handle breadth; deep reasoning is reserved for conflict nodes.",
        "primary_product_claim": "Research mode returns a report; ForkLens returns the decision surface and the branches not taken.",
    }
    return canvas


def relocation_demo() -> Canvas:
    objective = (
        "Maya is a 31-year-old product manager relocating to the Bay Area for a hybrid AI startup role. "
        "She needs to be in SoMa 2 to 3 days per week. Her max rent is $4,200/month. She has a dog, "
        "wants walkability, wants access to nature, and does not want a commute that ruins her week. "
        "She is comparing Hayes Valley, Mission Dolores, Noe Valley, Rockridge, Berkeley, and San Mateo. "
        "Where should Maya live if she wants the best balance of commute, rent, safety, walkability, "
        "dog-friendly lifestyle, access to nature, and downside risk?"
    )
    canvas = Canvas(
        id="demo-maya-bay-area-relocation",
        title="ForkLens Demo: Maya's Bay Area Relocation",
        objective=objective,
        lanes=[
            "Objective",
            "Discovery",
            "Hayes Valley",
            "Mission Dolores",
            "Noe Valley",
            "Rockridge",
            "Berkeley",
            "San Mateo",
            "Dissent Lane",
            "Human Forks",
            "Recommendation",
        ],
        readme="This seed graph uses Maya's relocation prompt as the relatable customer demo. Refresh with live Perplexity calls before publishing as a public artifact.",
    )

    nodes = [
        Node(
            id="objective",
            type="objective",
            title="Maya's decision objective",
            lane="Objective",
            x=80,
            y=90,
            summary=objective,
            confidence=0.94,
            tags=["relocation", "subjective-search", "high-intent"],
            cost=CostTrace(route="human_seed", total_cost_usd=0),
        ),
        Node(
            id="breadth-search",
            type="search_batch",
            title="Neighborhood discovery pass",
            lane="Discovery",
            x=360,
            y=90,
            summary="Search commute patterns, rent ranges, walkability, parks, dog amenities, safety signals, local sentiment, and downside risks for each neighborhood.",
            confidence=0.88,
            tags=["search-api", "neighborhoods", "low-cost"],
            cost=CostTrace(route="search_api", model="search", tool_calls=36, total_cost_usd=0.18, latency_ms=9800),
            details={"why_this_route": "Use cheap breadth before paying for deeper synthesis. Most relocation questions need current web evidence, not long-context brute force."},
        ),
        Node(
            id="source-clusters",
            type="source_cluster",
            title="Source clusters",
            lane="Discovery",
            x=360,
            y=250,
            summary="Group apartment listings, transit maps, neighborhood guides, local forums, crime dashboards, park maps, and commute calculators into reusable evidence clusters.",
            confidence=0.82,
            tags=["source-cache", "citations", "local-data"],
            sources=[
                _source("BART station information", "https://www.bart.gov/stations", "Transit source to refresh in live runs."),
                _source("SFMTA trip planning", "https://www.sfmta.com/getting-around/trip-planning", "San Francisco transit source to refresh in live runs."),
                _source("Walk Score", "https://www.walkscore.com/", "Walkability source to refresh in live runs."),
                _source("Niche neighborhood data", "https://www.niche.com/places-to-live/", "Neighborhood quality source to refresh in live runs."),
            ],
            cost=CostTrace(route="source_cluster", model="search+dedupe", tool_calls=12, total_cost_usd=0.035, latency_ms=6200),
        ),
        Node(
            id="hayes-claim",
            type="claim",
            title="Hayes Valley: commute and energy",
            lane="Hayes Valley",
            x=690,
            y=40,
            summary="Strongest if Maya optimizes SoMa commute, urban energy, restaurants, and walkability. The tradeoff is price, smaller spaces, and a higher chance that daily dog logistics feel constrained.",
            confidence=0.69,
            tags=["commute", "walkability", "price-risk"],
            cost=CostTrace(route="sonar", model="sonar-pro", input_tokens=3100, output_tokens=680, total_cost_usd=0.014, latency_ms=6500),
        ),
        Node(
            id="mission-claim",
            type="claim",
            title="Mission Dolores: social life and parks",
            lane="Mission Dolores",
            x=690,
            y=155,
            summary="Likely strongest for social energy, food, Dolores Park access, and car-light living. The hidden risk is noise, weekend crowding, and uneven block-by-block comfort.",
            confidence=0.66,
            tags=["parks", "social", "block-level-risk"],
            cost=CostTrace(route="sonar", model="sonar-pro", input_tokens=3000, output_tokens=660, total_cost_usd=0.013, latency_ms=6100),
        ),
        Node(
            id="noe-claim",
            type="claim",
            title="Noe Valley: dog-friendly routine",
            lane="Noe Valley",
            x=690,
            y=270,
            summary="A safer-feeling, dog-friendly daily routine with access to parks and calmer streets. The commute may become the weekly tax if SoMa days cluster during peak hours.",
            confidence=0.7,
            tags=["dog-friendly", "calm", "commute-risk"],
            cost=CostTrace(route="sonar", model="sonar-pro", input_tokens=3050, output_tokens=690, total_cost_usd=0.014, latency_ms=6400),
        ),
        Node(
            id="rockridge-claim",
            type="claim",
            title="Rockridge: space and BART tradeoff",
            lane="Rockridge",
            x=690,
            y=385,
            summary="A strong candidate if Maya values space, trees, restaurants, dog walks, and BART access. The tradeoff is cross-bay commute reliability and losing spontaneous SF social proximity.",
            confidence=0.71,
            tags=["space", "bart", "cross-bay-risk"],
            cost=CostTrace(route="sonar", model="sonar-pro", input_tokens=3150, output_tokens=700, total_cost_usd=0.014, latency_ms=6600),
        ),
        Node(
            id="berkeley-claim",
            type="claim",
            title="Berkeley: nature and character",
            lane="Berkeley",
            x=690,
            y=500,
            summary="Good for nature access, character, food, and a less corporate daily rhythm. The commute and social distance from SF are the load-bearing downsides.",
            confidence=0.62,
            tags=["nature", "character", "distance-risk"],
            cost=CostTrace(route="sonar", model="sonar-pro", input_tokens=2950, output_tokens=640, total_cost_usd=0.013, latency_ms=6000),
        ),
        Node(
            id="sanmateo-claim",
            type="claim",
            title="San Mateo: practical but maybe too quiet",
            lane="San Mateo",
            x=690,
            y=615,
            summary="Practical if Maya wants a cleaner commute pattern by Caltrain or car, more predictability, and access down the Peninsula. The risk is that it may under-deliver on urban energy and walkable spontaneity.",
            confidence=0.6,
            tags=["practical", "peninsula", "vibe-risk"],
            cost=CostTrace(route="sonar", model="sonar-pro", input_tokens=3000, output_tokens=650, total_cost_usd=0.013, latency_ms=6100),
        ),
        Node(
            id="dissent-commute",
            type="counterclaim",
            title="Blind spot: commute math lies",
            lane="Dissent Lane",
            x=1030,
            y=210,
            summary="Average commute estimates hide transfer pain, missed trains, dog-care timing, rainy days, and late meetings. ForkLens should require a simulated Tuesday and Thursday commute before ranking.",
            confidence=0.76,
            tags=["blind-spot", "commute", "lived-experience"],
            cost=CostTrace(route="adversarial_search", model="search+sonar", tool_calls=7, input_tokens=2200, output_tokens=560, total_cost_usd=0.042, latency_ms=12900),
        ),
        Node(
            id="dissent-vibes",
            type="counterclaim",
            title="Blind spot: vibes are evidence",
            lane="Dissent Lane",
            x=1030,
            y=355,
            summary="A ranked answer can miss whether Maya will actually like her Tuesday night. Local forums, street-level walks, park routines, and coffee/grocery paths belong in the evidence graph.",
            confidence=0.73,
            tags=["blind-spot", "vibes", "subjective-search"],
            cost=CostTrace(route="adversarial_search", model="search+sonar", tool_calls=6, input_tokens=2050, output_tokens=530, total_cost_usd=0.038, latency_ms=11800),
        ),
        Node(
            id="score-options",
            type="computation",
            title="Preference-weighted ranking",
            lane="Human Forks",
            x=1300,
            y=180,
            summary="Compute rankings for commute-first, dog-and-nature-first, social-energy-first, and least-regret strategies. Do not pretend one ranking is objectively correct.",
            confidence=0.84,
            tags=["scoring", "preferences", "sandbox"],
            cost=CostTrace(route="local_sandbox_adapter", model="python", total_cost_usd=0.0, latency_ms=85),
            details={
                "commute_first": {"commute": 0.4, "rent": 0.2, "walkability": 0.15, "safety": 0.15, "vibes": 0.1},
                "dog_nature_first": {"dog": 0.3, "nature": 0.25, "space": 0.2, "commute": 0.15, "rent": 0.1},
                "least_regret": {"commute": 0.25, "safety": 0.2, "rent": 0.2, "walkability": 0.15, "dog": 0.1, "vibes": 0.1},
            },
        ),
        Node(
            id="fork-priority",
            type="fork",
            title="Human fork: what can Maya not trade off?",
            lane="Human Forks",
            x=1300,
            y=390,
            summary="Pause before recommending. If commute must be easy, SF neighborhoods win. If dog-friendly routine matters most, Noe or Rockridge rise. If social energy matters, Hayes or Mission stay high.",
            status="needs_human",
            confidence=0.92,
            tags=["fork", "human-decision", "preference"],
            details={
                "options": [
                    "Protect commute and weekday energy",
                    "Protect dog-friendly routine and nature access",
                    "Protect social life and city feel",
                    "Minimize regret across all categories",
                ]
            },
        ),
        Node(
            id="recommendation",
            type="decision",
            title="Recommendation: shortlist by tradeoff",
            lane="Recommendation",
            x=1630,
            y=250,
            summary="Start with Hayes Valley and Mission Dolores if Maya wants commute and energy. Start with Noe Valley or Rockridge if she wants a durable dog-friendly routine. Treat San Mateo and Berkeley as branch tests, not defaults.",
            confidence=0.82,
            tags=["final", "decision-surface", "relocation"],
            cost=CostTrace(route="agent_synthesis", model="fast-search+sonar-pro", input_tokens=5200, output_tokens=1150, total_cost_usd=0.032, latency_ms=8400),
        ),
        Node(
            id="metrics",
            type="metric",
            title="Token economics ledger",
            lane="Recommendation",
            x=1630,
            y=455,
            summary="Relocation target: under $0.50, first useful neighborhood card under 10s, first fork under 60s, and every recommendation tied to sources or explicit preference weights.",
            confidence=0.9,
            tags=["metrics", "token-value-per-watt"],
            details={
                "target_cost_per_objective_usd": 0.50,
                "target_time_to_first_canvas_node_ms": 10000,
                "target_time_to_first_conflict_fork_ms": 60000,
                "target_deep_research_escalation_rate": 0.1,
                "target_broken_citation_rate": 0,
            },
        ),
    ]

    edges = [
        Edge("objective", "breadth-search", "decompose", "routes"),
        Edge("objective", "source-clusters", "collect evidence", "routes"),
        Edge("breadth-search", "hayes-claim", "neighborhood lane", "supports"),
        Edge("breadth-search", "mission-claim", "neighborhood lane", "supports"),
        Edge("breadth-search", "noe-claim", "neighborhood lane", "supports"),
        Edge("breadth-search", "rockridge-claim", "neighborhood lane", "supports"),
        Edge("breadth-search", "berkeley-claim", "neighborhood lane", "supports"),
        Edge("breadth-search", "sanmateo-claim", "neighborhood lane", "supports"),
        Edge("hayes-claim", "dissent-commute", "commute reality", "contradicts"),
        Edge("rockridge-claim", "dissent-commute", "cross-bay risk", "contradicts"),
        Edge("mission-claim", "dissent-vibes", "block-level reality", "contradicts"),
        Edge("noe-claim", "score-options", "score", "routes"),
        Edge("rockridge-claim", "score-options", "score", "routes"),
        Edge("dissent-commute", "fork-priority", "requires choice", "forks"),
        Edge("dissent-vibes", "fork-priority", "requires choice", "forks"),
        Edge("score-options", "fork-priority", "ranking depends on weights", "forks"),
        Edge("fork-priority", "recommendation", "selected tradeoff", "resolves"),
        Edge("recommendation", "metrics", "prove efficiency", "supports"),
    ]

    canvas.nodes = nodes
    canvas.edges = edges
    canvas.metrics = {
        "estimated_total_cost_usd": round(sum((node.cost.total_cost_usd if node.cost else 0) for node in nodes), 3),
        "estimated_latency_ms_sum": sum((node.cost.latency_ms or 0) for node in nodes if node.cost),
        "deep_research_escalation_rate": 0.0,
        "frontier_token_displacement": "Search handles broad current data; synthesis only turns evidence into preference-aware cards.",
        "primary_product_claim": "Chat returns a ranked neighborhood list; ForkLens returns the tradeoff surface behind the move.",
    }
    return canvas
